model:
  base_learning_rate: 2.0e-06
  target: dmm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "jpg"
    cond_stage_key: "txt"
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: True

    unet_config:
      target: dmm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_checkpoint: True
        use_fp16: False
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

    first_stage_config:
      target: dmm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          #attn_type: "vanilla-xformers"
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: dmm.modules.encoders.modules.FrozenOpenCLIPEmbedder
      params:
        freeze: True
        layer: "penultimate"

data:
  target: solver.pl_solver.DataModuleFromConfig
  params:
    batch_size: 1
    # num_workers: 1
    wrap: false
    train:
      target: dmm.dataloader.MTG.AudioFolder
      params:
        root: /home/hu/database/MTG_audio
        subset: 'autotagging'
        tr_val: 'train'
        type: 'audio'
        split: 0
    # test:
    #   target: dmm.dataloader.MTG.AudioFolder
    #   params:
    #     root: /home/hu/database/MTG_audio
    #     subset: 'autotagging'
    #     tr_val: 'validation'
    #     type: 'audio'
    #     split: 0

lightning:
  callbacks:
    image_logger:
      target: solver.pl_solver.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    gpus: 1
    # precision: 16
    accelerator: "gpu"